# Generated by Django 6.0 on 2025-12-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="chunk_overlap",
            field=models.IntegerField(
                default=100, verbose_name="Chevauchement des chunks"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="chunk_size",
            field=models.IntegerField(default=800, verbose_name="Taille des chunks"),
        ),
        migrations.AddField(
            model_name="user",
            name="retrieval_k",
            field=models.IntegerField(
                default=5, verbose_name="Nombre de chunks à récupérer"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nom complet"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.DeleteModel(
            name="UserPreference",
        ),
    ]
