# Generated by Django 6.0 on 2025-12-18 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chunk",
            options={
                "ordering": ["pdf", "chunk_index"],
                "verbose_name": "Chunk",
                "verbose_name_plural": "Chunks",
            },
        ),
        migrations.AlterModelOptions(
            name="pdffile",
            options={
                "ordering": ["-upload_date"],
                "verbose_name": "Fichier PDF",
                "verbose_name_plural": "Fichiers PDF",
            },
        ),
        migrations.AlterField(
            model_name="chunk",
            name="chunk_index",
            field=models.IntegerField(verbose_name="Index du chunk"),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="chunk_text",
            field=models.TextField(verbose_name="Texte du chunk"),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="end_char",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Caractère de fin"
            ),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="page_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Numéro de page"
            ),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="pdf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="document.pdffile",
                verbose_name="PDF",
            ),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="start_char",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Caractère de début"
            ),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="token_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Nombre de tokens"
            ),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="vector_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID du vecteur"
            ),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="file_path",
            field=models.CharField(max_length=500, verbose_name="Chemin du fichier"),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="file_size",
            field=models.BigIntegerField(verbose_name="Taille du fichier"),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="filename",
            field=models.CharField(max_length=255, verbose_name="Nom du fichier"),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="metadata",
            field=models.JSONField(blank=True, null=True, verbose_name="Métadonnées"),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="original_filename",
            field=models.CharField(max_length=255, verbose_name="Nom original"),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="page_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Nombre de pages"
            ),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("processing", "En traitement"),
                    ("completed", "Terminé"),
                    ("failed", "Échoué"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Statut de traitement",
            ),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="total_chunks",
            field=models.IntegerField(default=0, verbose_name="Nombre total de chunks"),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="upload_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload"),
        ),
        migrations.AlterField(
            model_name="pdffile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pdf_files",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(
                fields=["pdf", "chunk_index"], name="chunks_pdf_id_6498e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(fields=["user"], name="chunks_user_id_8b53b5_idx"),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(fields=["vector_id"], name="chunks_vector__3a8779_idx"),
        ),
        migrations.AddIndex(
            model_name="pdffile",
            index=models.Index(
                fields=["user", "processing_status"],
                name="pdf_files_user_id_5f3d2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pdffile",
            index=models.Index(
                fields=["upload_date"], name="pdf_files_upload__c1ae32_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="chunk",
            table="chunks",
        ),
        migrations.AlterModelTable(
            name="pdffile",
            table="pdf_files",
        ),
    ]
