# Generated by Django 6.0 on 2025-12-18 13:29

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Session de chat",
                "verbose_name_plural": "Sessions de chat",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="pdf_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                verbose_name="IDs des PDFs",
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="chunk_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                verbose_name="IDs des chunks utilisés",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="metadata",
            field=models.JSONField(blank=True, null=True, verbose_name="Métadonnées"),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "Utilisateur"), ("assistant", "Assistant")],
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatsession",
                verbose_name="Session",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="tokens_used",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Tokens utilisés"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "is_active"], name="chat_sessio_user_id_d84cc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["updated_at"], name="chat_sessio_updated_5b0264_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "created_at"], name="messages_session_1b3070_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["user"], name="messages_user_id_d457bc_idx"),
        ),
        migrations.AlterModelTable(
            name="chatsession",
            table="chat_sessions",
        ),
        migrations.AlterModelTable(
            name="message",
            table="messages",
        ),
    ]
