# Generated by Django 4.2.27 on 2026-01-20 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_chatsession_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(choices=[('positive', 'Utile'), ('negative', 'Incorrecte')], max_length=20, verbose_name='Type de feedback')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire optionnel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chat.message', verbose_name='Message concerné')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Feedback message',
                'verbose_name_plural': 'Feedbacks messages',
                'db_table': 'message_feedbacks',
                'unique_together': {('user', 'message')},
            },
        ),
    ]
